import {b64Buf, strBuf} from "./test-util";

export const prog_echo = b64Buf(
    "AGFzbQEAAAABDQNgAX8AYAAAYAF/AX8CEwEDZW52C3BwdHcxX2Fib3J0AAADBAMBAgIFAwEAAgYO" +
    "An8AQaCIBAt/AEGSCAsHXQcGbWVtb3J5AgALX19oZWFwX2Jhc2UDAApfX2RhdGFfZW5kAwEKcHB0" +
    "dzFfaW5pdAABDHBwdHcxX21hbGxvYwACDXBwdHcxX2NsZWFudXAAAQlwcHR3MV9ydW4AAwquAQMD" +
    "AAELRwECf0GACEGACCgCACIBQQAgAGtBB3EgAGpqIgA2AgACQCAAQRB2IgA/ACICSwRAIAAgAmtA" +
    "AEF/Rg0BCyABDwtBhAgQAAALYAEEfyAAKAIIQQN0QQRyEAIiAyAAKAIINgIAIAAoAggEQCAAQQxq" +
    "IQEgA0EEaiECA0AgAiABKQIANwIAIAFBCGohASACQQhqIQIgBEEBaiIEIABBCGooAgBJDQALCyAD" +
    "CwsdAgBBgAgLAyAEAQBBhAgLDU91dCBvZiBtZW1vcnk="
);

export const prog_abort = b64Buf(
    "AGFzbQEAAAABDQNgAX8AYAAAYAF/AX8CEwEDZW52C3BwdHcxX2Fib3J0AAADBAMBAgIFAwEAAgYO" +
    "An8AQaCIBAt/AEGSCAsHXQcGbWVtb3J5AgALX19oZWFwX2Jhc2UDAApfX2RhdGFfZW5kAwEKcHB0" +
    "dzFfaW5pdAABDHBwdHcxX21hbGxvYwACDXBwdHcxX2NsZWFudXAAAQlwcHR3MV9ydW4AAwpVAwMA" +
    "AQtHAQJ/QYAIQYAIKAIAIgFBACAAa0EHcSAAamoiADYCAAJAIABBEHYiAD8AIgJLBEAgACACa0AA" +
    "QX9GDQELIAEPC0GECBAAAAsHAEEAEAAACwsdAgBBgAgLAyAEAQBBhAgLDU91dCBvZiBtZW1vcnk="
);

export const hello_world = strBuf("Hello World!");
